### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by gpiechnik2** [wosp-io/xk6-playwright#1]
Hi,
I think it would be useful to update the README file with the following information:
For the tool to work, the browsers and OS dependencies must be installed locally. You can use the `go run github.com/playwright-community/playwright-go/cmd/playwright@latest install --with-deps` command for this. 

Additionally, instead of: `xk6 build --output xk6-playwright --with github.com/wosp-io/xk6-playwright` better use `xk6 build --output xk6-playwright.exe --with github.com/wosp-io/xk6-playwright`. I know it's a small change, but if someone is using windows, the file will not be executed.

**Comment by nicholasvuono** [comment]
I appreciate the recommendations! There is definitely room to improve upon existing documentation. 

We should definitely make the distinction and set an example for Windows users, using the example you suggested.

In terms of the dependencies, that is another oversight that needs to be addressed! Thanks again for bringing it to our attention 🙏🏻
