### ISSUE TITLE
Question - How the container gets the script file?

### ISSUE THREAD

**Issue by rakeshnambiar** [wosp-io/xk6-playwright#11]
I think the command `docker run --rm -i nickvuono/xk6-playwright run script.js` is not enough for the beginners like me to starts with. Please could you tell me, how the script file will be uploaded to the container?

Similarly when I run the test by building it locally, the K6 metrics are not displaying. How do I view it?

```
          /\      |‾‾| /‾‾/   /‾‾/   
     /\  /  \     |  |/  /   /  /    
    /  \/    \    |     (   /   ‾‾\  
   /          \   |  |\  \ |  (‾)  | 
  / __________ \  |__| \__\ \_____/ .io

  execution: local
     script: script.js
     output: -

  scenarios: (100.00%) 1 scenario, 10 max VUs, 25s max duration (incl. graceful stop):
           * example_scenario: 200 iterations shared among 10 VUs (maxDuration: 10s, startTime: 10s, gracefulStop: 5s)
```

**Comment by nicholasvuono** [comment]
Hey in line with a maintenance I will slowly be adding more examples and documentation. Apologies for the delay on responding to this! I will create a branch and post it in a few hours that will be worked on and house what you are looking for!

Thank you for bringing this to my attention 🙏🏻 hope this will help

**Comment by nicholasvuono** [comment]
@rakeshnambiar The updated repo should be complete and fully functional! Feel free to follow the new steps in the README.md and use the examples provided in the examples folder of this repo!

I will close this out but feel free to open another issue if problems still persist!
