### ISSUE TITLE
handling driver and browser downloads

### ISSUE THREAD

**Issue by cwegener** [wosp-io/xk6-playwright#7]
Very interesting project. Thanks for writing and sharing this extension.

What would be the best way to deal with playwright's downloading of drivers and browsers?

playwright-go has the `err := playwright.Install()` convenience function, but could this function be integrated into a k6 extension somehow? Obviously the downloading part of the playwright dependencies should not have anything to do with any of the available modes of k6.

**Comment by nicholasvuono** [comment]
Hmmm this is a very interesting question. It is something I will have to look into further. Not sure what the best way to handle this would be because I feel as though installing the browsers should never be a part of the k6 script itself. Maybe it could be a part of the build binary? Did you have any thoughts on this?

**Comment by nicholasvuono** [comment]
As a work around for now the docker image comes with everything preinstalled hopefully that works for you and others until we can figure out the proper solution 🙏🏻 !

**Comment by cwegener** [comment]
Well, for now i added `err := playwright.Install()` in front of every `playwright.Run()` invocation :joy: and does the job for kicking the tires of this nice extension.

I have thought about whether the download should happen at build time, but I couldn't immediately figure out how to accomplish that in a way such that "it just works" when the custom xk6-playwright binary is being executed.

My previous experience has been mostly with selenium and webdriver. In the webdriver world, I would usually prefer to have my drivers and browser installations managed by the operating system tooling, which most of the webdriver's allowed to be configured in one way or another.

I wonder if playwright in general allows for driver installations to be managed completely outside of playwright.
I'm still relatively new to playwright.

**Comment by nicholasvuono** [comment]
Personal belief, but I think one of the beauties of using playwright over things like selenium is that browsers comes packaged with the tool itself. This allows for an easier development experience and it will also allow the people maintaining playwright to ensure the version is compatible with whatever browser version it come packaged with. Comparing this to selenium where you have to ensure your drivers are compatible with the installed browsers and the particular version of selenium.

I'm glad you are enjoying the extension! And apologies for the awkward workaround 😂

Until I figure out how to bundle the compatible browsers with a binary, a more elegant way (and more similar to selenium) would be to point the `playwright.Launch()` invocation to an already installed chromium browser on your machine. 

An example of this within a k6 script would be as follows:

```
import pw from 'k6/x/playwright';

export default function () {
  pw.launch({
     executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
  })
}
```

As long as your browser version is compatible with the playwright-go version used for this extension `v0.2000.1` I believe you should be able to get the best of both worlds. You can manage the browsers with the operating system tooling, and use them within your k6 scripts!

I think any Chromium based browser above version `100.x.x` should work, but as of right now I'm see this as the documented version for best compatibility:  `Chromium 105.0.5195.19`

Let me know if this helps, and is more closely in line with what you are looking for!
