### ISSUE TITLE
Multiple VUs

### ISSUE THREAD

**Issue by driesie** [wosp-io/xk6-playwright#8]
Hi,

I need to run a performance test for multiple VUs.

When I run my test for 2 VUs it opens two browsers (running headed for testing purposes) but it only interacts with one of the browsers.

It almost looks like it gets confused because two are running concurrently.

This is part of my code that needs to run and as I stated, only one of the browsers performs the actions.

pw.launch({ headless: false })
    pw.newPage()
    pw.goto(redirectUrl)

    pw.waitForSelector("input[name='cvc']", {state: 'visible'})
    pw.type("input[name='cvc']", cvv)

    pw.waitForSelector("button[type='submit']", {state: 'visible'})
    pw.click("button[type='submit']")

**Comment by nicholasvuono** [comment]
Hey 👋!

Can you give a specific use case for running multiple vus at the same time? This kind of goes against our philosophy for performance testing using browsers, but we are willing to listen if there is a great need for it

For now please see our answer to the following issue opened in the past and see if it answers any questions: https://github.com/wosp-io/xk6-playwright/issues/2

**Comment by driesie** [comment]
In our application there are two API calls that gets performed and the second one returns a payment page URL that the user needs to navigate to.

On this page there are payment details to enter, a redirect happens to a 3DS page where a password is entered after which you are redirected back to the payment page which will show the payment status.

I am not sure how I can stress test this flow without the interaction with the browser from happening.

**Comment by nicholasvuono** [comment]
Hmm okay I see now that makes sense. It's a bit tricky. Have you tried going through the workflow yourself and recording a .har file? Generally you can capture all the network requests in order for that specific workflow and kick them off in the same order using k6 groups. Might be tricky with the 3DS redirects though but I would give that some exploration

**Comment by nicholasvuono** [comment]
If you find it captures the proper requests, I would gladly help you develop a dynamic script example using a .har file 😊
