### ISSUE TITLE
Needed to maintain listing in k6 Extensions Registry

### ISSUE THREAD

**Issue by javaducky** [wosp-io/xk6-playwright#9]
We've recently updated the requirements for maintaining an extension within the listing on our site. As such, please address the following items to maintain your listing within the registry:

* add an `examples` directory containing k6 test scripts making use of your extension
* needs to build with a recent version of k6; minimum v0.43

For more information on these and other listing requirements, please take a look at the [registry requirements](https://k6.io/docs/extensions/explanations/about-the-extensions-registry/).

**Comment by nicholasvuono** [comment]
Thank you for the update! I will be working on this ASAP!

**Comment by nicholasvuono** [comment]
Closing. This has been completed!
